BEGIN
START TRANSACTION;
  UPDATE BT_SEQUENCE SET SEQUENCE_DATE = DATE_FORMAT(now(),'%Y%m%d'), SEQUENCE_VALUE = 0 WHERE SEQUENCE_DATE != DATE_FORMAT(now(),'%Y%m%d') AND SEQUENCE_NAME = PARAM_SEQUENCE_NAME;
	UPDATE BT_SEQUENCE SET SEQUENCE_VALUE = SEQUENCE_VALUE + PARAM_INCREMENT_COUNT WHERE SEQUENCE_NAME = PARAM_SEQUENCE_NAME AND SEQUENCE_DATE = DATE_FORMAT(now(),'%Y%m%d');
	SELECT SEQUENCE_VALUE INTO OUTPUT_SEQUENCE_VALUE FROM BT_SEQUENCE WHERE SEQUENCE_NAME = PARAM_SEQUENCE_NAME;
	SELECT DATE_FORMAT(now(),'%Y%m%d%H%i%s') INTO OUTPUT_NOW_DATETIME;
COMMIT;
END