BEGIN
	UPDATE BT_SEQUENCE S SET S.SEQUENCE_VALUE = S.SEQUENCE_VALUE + 1 WHERE S.SEQUENCE_NAME = SEQUENCE_NAME;
    SELECT S.SEQUENCE_VALUE FROM BT_SEQUENCE S WHERE S.SEQUENCE_NAME = SEQUENCE_NAME;
COMMIT;
END